spring:
  datasource:
    url: jdbc:mysql://localhost:32768/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    show-sql: true
  aop:
    proxy-target-class: true
  rabbitmq:
    host: 127.0.0.1
    port: 56720
    username: guest
    password: guest
    virtual-host: /

socket-server:
  url: http://localhost:9092
